### ISSUE TITLE
how to do a prediction some future time ahead 

### ISSUE THREAD

**Issue by wilbertmatthew** [necst/Echobay#1]
Hi,

I have built a prediction model using the example laser data. I would like to use the model optimization files as weights to do a prediction on the laser data for some days in the future. I am using the compute parameter (./main compute /home/wilbert/Echobay/src/wilbert1/ out). I don't understand where I go from here. I notice the test file is included in the compute function.  Why? How do I predict steps ahead without a test data file?

Ubuntu 16.04

Thanks

Wilbert Jackson

**Comment by LucaCerina** [comment]
Hello Wilbert,
If I understood your issue correctly, you would like to predict values in the future by feeding the last prediction as the input right?
Unfortunately this is a feature that has not been implemented yet.

In `compute` we use the test data file (or any other file with the same format) as input to the ESN, and it will predict values according to the trained model (e.g., 1 step ahead).

Instead if you want a model that performs n-step ahead prediction you need to prepare the data accordingly and train the model for that. Right now the laser example performs 1-step prediction if you look at the `get_laser_data.py` script, lines 46-47. Moving TestLabel data forward will change the number of steps in the future.

Hope that helps you.
